/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_SO;

import Proyecto_SO.Clases.PlantaRyM.HBO2;
import Proyecto_SO.Clases.PlantaTLOU.HBO1;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author frand
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     * 
     */
    
    private final Actualizador up;
    HBO1 hbo = new HBO1();
    HBO2 hbo2 = new HBO2(); 
    
    public Dashboard() throws FileNotFoundException, InterruptedException, ParseException{
        initComponents();
        this.up = new Actualizador(this, this.hbo);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Produccion = new javax.swing.JLabel();
        Empleados = new javax.swing.JLabel();
        NumIntrosRM = new javax.swing.JTextField();
        NumIniciosRM = new javax.swing.JTextField();
        NumCreditosRM = new javax.swing.JTextField();
        NumCierresRM = new javax.swing.JTextField();
        NumIntros = new javax.swing.JTextField();
        NumPTwistRM = new javax.swing.JTextField();
        NumCapRM = new javax.swing.JTextField();
        IntrosTLOU = new javax.swing.JLabel();
        NumInicios = new javax.swing.JTextField();
        IniciosTLOU = new javax.swing.JLabel();
        NumCred = new javax.swing.JTextField();
        CredTLOU = new javax.swing.JLabel();
        NumPlot = new javax.swing.JTextField();
        PlotTLOU = new javax.swing.JLabel();
        NumCierre = new javax.swing.JTextField();
        CierreTLOU = new javax.swing.JLabel();
        CapsTLOU = new javax.swing.JTextField();
        CapitulosTLOU = new javax.swing.JLabel();
        NumEmpIntros = new javax.swing.JTextField();
        EmpIntrosTLOU = new javax.swing.JLabel();
        NumEmpInicios = new javax.swing.JTextField();
        EmpIniciosTLOU = new javax.swing.JLabel();
        NumEmpCred = new javax.swing.JTextField();
        EmpCredsTLOU = new javax.swing.JLabel();
        NumEmpPlot = new javax.swing.JTextField();
        EmpPlotTLO = new javax.swing.JLabel();
        NumEmpCierre = new javax.swing.JTextField();
        EmpCierreTLOU = new javax.swing.JLabel();
        NumEmpDispo = new javax.swing.JTextField();
        EmpDispoTLOU = new javax.swing.JLabel();
        NumEmpEnsamblador = new javax.swing.JTextField();
        EmpEnsambladorTLOU = new javax.swing.JLabel();
        EmpIntroDesp = new javax.swing.JButton();
        EmpInicioDesp = new javax.swing.JButton();
        EmpCredDesp = new javax.swing.JButton();
        EmpPlotDesp = new javax.swing.JButton();
        EmpCierreDesp = new javax.swing.JButton();
        EmpEnsambladorDesp = new javax.swing.JButton();
        EmpIntro = new javax.swing.JButton();
        EmpInicio = new javax.swing.JButton();
        EmpCred = new javax.swing.JButton();
        EmpPlot = new javax.swing.JButton();
        EmpCierre = new javax.swing.JButton();
        EmpEnsamblador = new javax.swing.JButton();
        Produccion4 = new javax.swing.JLabel();
        PMStatus = new javax.swing.JTextField();
        ProyectMTLOU = new javax.swing.JLabel();
        DirTLOU = new javax.swing.JTextField();
        DirTextTLOU = new javax.swing.JLabel();
        GananciasTLOU = new javax.swing.JTextField();
        GananciasTextTLOU = new javax.swing.JLabel();
        DiasRestantesTLOU = new javax.swing.JTextField();
        DiasRestantesTextTLOU = new javax.swing.JLabel();
        FallasPM = new javax.swing.JTextField();
        Fallas = new javax.swing.JLabel();
        GastosMensuales = new javax.swing.JTextField();
        GastosM = new javax.swing.JLabel();
        UltimoLoteTLOU = new javax.swing.JTextField();
        GananciasTextTLOU1 = new javax.swing.JLabel();
        GananciasUL = new javax.swing.JTextField();
        UL = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        IntrosRM = new javax.swing.JLabel();
        IniciosRM = new javax.swing.JLabel();
        CredRM = new javax.swing.JLabel();
        PlotRM = new javax.swing.JLabel();
        CierreRM = new javax.swing.JLabel();
        CapitulosRM = new javax.swing.JLabel();
        Empleados1 = new javax.swing.JLabel();
        EmpEmbRM = new javax.swing.JTextField();
        EmpCierreRM = new javax.swing.JTextField();
        EmpPTwistRM = new javax.swing.JTextField();
        EmpCredRM = new javax.swing.JTextField();
        EmpInicioRM = new javax.swing.JTextField();
        EmpIntroRM = new javax.swing.JTextField();
        EmpIntroDesp2 = new javax.swing.JButton();
        EmpIntroDesp1 = new javax.swing.JButton();
        ProyectMTLOU1 = new javax.swing.JLabel();
        FinanzasRM = new javax.swing.JTextField();
        DiasRestantesTextTLOU1 = new javax.swing.JLabel();
        DiasRestantesRM = new javax.swing.JTextField();
        ProyectMTLOU2 = new javax.swing.JLabel();
        PMStatuRM = new javax.swing.JTextField();
        ProyectMTLOU3 = new javax.swing.JLabel();
        DirStatuRM1 = new javax.swing.JTextField();
        ProyectMTLOU4 = new javax.swing.JLabel();
        GananciasRM1 = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Produccion.setForeground(new java.awt.Color(255, 255, 255));
        Produccion.setText("Produccion 2");
        jPanel1.add(Produccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        Empleados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Empleados.setText("Empleados");
        jPanel1.add(Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        NumIntrosRM.setEditable(false);
        NumIntrosRM.setBackground(new java.awt.Color(0, 39, 76));
        NumIntrosRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumIntrosRM.setForeground(new java.awt.Color(255, 255, 255));
        NumIntrosRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumIntrosRM.setText("0");
        NumIntrosRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIntrosRMActionPerformed(evt);
            }
        });
        jPanel1.add(NumIntrosRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 30, 30));

        NumIniciosRM.setEditable(false);
        NumIniciosRM.setBackground(new java.awt.Color(0, 39, 76));
        NumIniciosRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumIniciosRM.setForeground(new java.awt.Color(255, 255, 255));
        NumIniciosRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumIniciosRM.setText("0");
        NumIniciosRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIniciosRMActionPerformed(evt);
            }
        });
        jPanel1.add(NumIniciosRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 30, 30));

        NumCreditosRM.setEditable(false);
        NumCreditosRM.setBackground(new java.awt.Color(0, 39, 76));
        NumCreditosRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCreditosRM.setForeground(new java.awt.Color(255, 255, 255));
        NumCreditosRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCreditosRM.setText("0");
        NumCreditosRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCreditosRMActionPerformed(evt);
            }
        });
        jPanel1.add(NumCreditosRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 30, 30));

        NumCierresRM.setEditable(false);
        NumCierresRM.setBackground(new java.awt.Color(0, 39, 76));
        NumCierresRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCierresRM.setForeground(new java.awt.Color(255, 255, 255));
        NumCierresRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCierresRM.setText("0");
        NumCierresRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCierresRMActionPerformed(evt);
            }
        });
        jPanel1.add(NumCierresRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 30, 30));

        NumIntros.setEditable(false);
        NumIntros.setBackground(new java.awt.Color(0, 39, 76));
        NumIntros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumIntros.setForeground(new java.awt.Color(255, 255, 255));
        NumIntros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumIntros.setText("0");
        NumIntros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIntrosActionPerformed(evt);
            }
        });
        jPanel1.add(NumIntros, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 30, 30));

        NumPTwistRM.setEditable(false);
        NumPTwistRM.setBackground(new java.awt.Color(0, 39, 76));
        NumPTwistRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumPTwistRM.setForeground(new java.awt.Color(255, 255, 255));
        NumPTwistRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPTwistRM.setText("0");
        NumPTwistRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPTwistRMActionPerformed(evt);
            }
        });
        jPanel1.add(NumPTwistRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 30, 30));

        NumCapRM.setEditable(false);
        NumCapRM.setBackground(new java.awt.Color(0, 39, 76));
        NumCapRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCapRM.setForeground(new java.awt.Color(255, 255, 255));
        NumCapRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCapRM.setText("0");
        NumCapRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCapRMActionPerformed(evt);
            }
        });
        jPanel1.add(NumCapRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 30, 30));

        IntrosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IntrosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        IntrosTLOU.setText("Intros");
        jPanel1.add(IntrosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        NumInicios.setEditable(false);
        NumInicios.setBackground(new java.awt.Color(0, 39, 76));
        NumInicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumInicios.setForeground(new java.awt.Color(255, 255, 255));
        NumInicios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumInicios.setText("0");
        NumInicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIniciosActionPerformed(evt);
            }
        });
        jPanel1.add(NumInicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 30, 30));

        IniciosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IniciosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        IniciosTLOU.setText("Inicios");
        jPanel1.add(IniciosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, -1));

        NumCred.setEditable(false);
        NumCred.setBackground(new java.awt.Color(0, 39, 76));
        NumCred.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCred.setForeground(new java.awt.Color(255, 255, 255));
        NumCred.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCred.setText("0");
        NumCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCredActionPerformed(evt);
            }
        });
        jPanel1.add(NumCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 30, 30));

        CredTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CredTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CredTLOU.setText("Creditos");
        jPanel1.add(CredTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        NumPlot.setEditable(false);
        NumPlot.setBackground(new java.awt.Color(0, 39, 76));
        NumPlot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumPlot.setForeground(new java.awt.Color(255, 255, 255));
        NumPlot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPlot.setText("0");
        NumPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPlotActionPerformed(evt);
            }
        });
        jPanel1.add(NumPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 30, 30));

        PlotTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlotTLOU.setForeground(new java.awt.Color(255, 255, 255));
        PlotTLOU.setText("Plot Twist");
        jPanel1.add(PlotTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        NumCierre.setEditable(false);
        NumCierre.setBackground(new java.awt.Color(0, 39, 76));
        NumCierre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCierre.setForeground(new java.awt.Color(255, 255, 255));
        NumCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCierre.setText("0");
        NumCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCierreActionPerformed(evt);
            }
        });
        jPanel1.add(NumCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 30, 30));

        CierreTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CierreTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CierreTLOU.setText("Cierres");
        jPanel1.add(CierreTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        CapsTLOU.setEditable(false);
        CapsTLOU.setBackground(new java.awt.Color(0, 39, 76));
        CapsTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapsTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CapsTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapsTLOU.setText("0");
        CapsTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapsTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(CapsTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 30, 30));

        CapitulosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapitulosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CapitulosTLOU.setText("Capitulos");
        jPanel1.add(CapitulosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        NumEmpIntros.setEditable(false);
        NumEmpIntros.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpIntros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpIntros.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpIntros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpIntros.setText("0");
        NumEmpIntros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpIntrosActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpIntros, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 30, 30));

        EmpIntrosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpIntrosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntrosTLOU.setText("Intros");
        jPanel1.add(EmpIntrosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, -1, -1));

        NumEmpInicios.setEditable(false);
        NumEmpInicios.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpInicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpInicios.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpInicios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpInicios.setText("0");
        NumEmpInicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpIniciosActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpInicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 30, 30));

        EmpIniciosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpIniciosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpIniciosTLOU.setText("Inicios");
        jPanel1.add(EmpIniciosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, -1, -1));

        NumEmpCred.setEditable(false);
        NumEmpCred.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpCred.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpCred.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpCred.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpCred.setText("0");
        NumEmpCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpCredActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 30, 30));

        EmpCredsTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpCredsTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpCredsTLOU.setText("Creditos");
        jPanel1.add(EmpCredsTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, -1, -1));

        NumEmpPlot.setEditable(false);
        NumEmpPlot.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpPlot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpPlot.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpPlot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpPlot.setText("0");
        NumEmpPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpPlotActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 30, 30));

        EmpPlotTLO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpPlotTLO.setForeground(new java.awt.Color(255, 255, 255));
        EmpPlotTLO.setText("Plot Twist");
        jPanel1.add(EmpPlotTLO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, -1));

        NumEmpCierre.setEditable(false);
        NumEmpCierre.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpCierre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpCierre.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpCierre.setText("0");
        NumEmpCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpCierreActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 30, 30));

        EmpCierreTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpCierreTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierreTLOU.setText("Cierres");
        jPanel1.add(EmpCierreTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, -1, -1));

        NumEmpDispo.setEditable(false);
        NumEmpDispo.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpDispo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpDispo.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpDispo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpDispo.setText("0");
        NumEmpDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpDispoActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 30, 30));

        EmpDispoTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpDispoTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpDispoTLOU.setText("Disponibles");
        jPanel1.add(EmpDispoTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, -1, -1));

        NumEmpEnsamblador.setEditable(false);
        NumEmpEnsamblador.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpEnsamblador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpEnsamblador.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpEnsamblador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpEnsamblador.setText("0");
        NumEmpEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 30, 30));

        EmpEnsambladorTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpEnsambladorTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpEnsambladorTLOU.setText("Ensamblador");
        jPanel1.add(EmpEnsambladorTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, -1, -1));

        EmpIntroDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntroDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpIntroDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntroDesp.setText("-");
        EmpIntroDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntroDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, 30));

        EmpInicioDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpInicioDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpInicioDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpInicioDesp.setText("-");
        EmpInicioDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpInicioDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpInicioDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, 30));

        EmpCredDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpCredDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpCredDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpCredDesp.setText("-");
        EmpCredDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCredDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCredDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, 30));

        EmpPlotDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpPlotDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpPlotDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpPlotDesp.setText("-");
        EmpPlotDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPlotDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpPlotDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, 30));

        EmpCierreDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpCierreDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpCierreDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierreDesp.setText("-");
        EmpCierreDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCierreDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCierreDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, -1, 30));

        EmpEnsambladorDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpEnsambladorDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpEnsambladorDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpEnsambladorDesp.setText("-");
        EmpEnsambladorDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpEnsambladorDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpEnsambladorDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, -1, 30));

        EmpIntro.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpIntro.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntro.setText("+");
        EmpIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, -1, 30));

        EmpInicio.setBackground(new java.awt.Color(0, 39, 76));
        EmpInicio.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpInicio.setForeground(new java.awt.Color(255, 255, 255));
        EmpInicio.setText("+");
        EmpInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpInicioActionPerformed(evt);
            }
        });
        jPanel1.add(EmpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, -1, 30));

        EmpCred.setBackground(new java.awt.Color(0, 39, 76));
        EmpCred.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpCred.setForeground(new java.awt.Color(255, 255, 255));
        EmpCred.setText("+");
        EmpCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCredActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, -1, 30));

        EmpPlot.setBackground(new java.awt.Color(0, 39, 76));
        EmpPlot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpPlot.setForeground(new java.awt.Color(255, 255, 255));
        EmpPlot.setText("+");
        EmpPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPlotActionPerformed(evt);
            }
        });
        jPanel1.add(EmpPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, -1, 30));

        EmpCierre.setBackground(new java.awt.Color(0, 39, 76));
        EmpCierre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpCierre.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierre.setText("+");
        EmpCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCierreActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, -1, 30));

        EmpEnsamblador.setBackground(new java.awt.Color(0, 39, 76));
        EmpEnsamblador.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpEnsamblador.setForeground(new java.awt.Color(255, 255, 255));
        EmpEnsamblador.setText("+");
        EmpEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(EmpEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, -1, 30));

        Produccion4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Produccion4.setForeground(new java.awt.Color(255, 255, 255));
        Produccion4.setText("Produccion");
        jPanel1.add(Produccion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        PMStatus.setEditable(false);
        PMStatus.setBackground(new java.awt.Color(0, 39, 76));
        PMStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PMStatus.setForeground(new java.awt.Color(255, 255, 255));
        PMStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PMStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMStatusActionPerformed(evt);
            }
        });
        jPanel1.add(PMStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 60, 120, 30));

        ProyectMTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProyectMTLOU.setForeground(new java.awt.Color(255, 255, 255));
        ProyectMTLOU.setText("Ganancias");
        jPanel1.add(ProyectMTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, -1, -1));

        DirTLOU.setEditable(false);
        DirTLOU.setBackground(new java.awt.Color(0, 39, 76));
        DirTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DirTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DirTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DirTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(DirTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 130, 120, 30));

        DirTextTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DirTextTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DirTextTLOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DirTextTLOU.setText("Director");
        jPanel1.add(DirTextTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 110, 120, -1));

        GananciasTLOU.setEditable(false);
        GananciasTLOU.setBackground(new java.awt.Color(0, 39, 76));
        GananciasTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasTLOU.setForeground(new java.awt.Color(255, 255, 255));
        GananciasTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GananciasTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(GananciasTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 160, 30));

        GananciasTextTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasTextTLOU.setForeground(new java.awt.Color(255, 255, 255));
        GananciasTextTLOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GananciasTextTLOU.setText("Ganancias totales");
        jPanel1.add(GananciasTextTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, -1));

        DiasRestantesTLOU.setEditable(false);
        DiasRestantesTLOU.setBackground(new java.awt.Color(0, 39, 76));
        DiasRestantesTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiasRestantesTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DiasRestantesTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiasRestantesTLOU.setText("0");
        DiasRestantesTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasRestantesTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(DiasRestantesTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, 40, 40));

        DiasRestantesTextTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiasRestantesTextTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DiasRestantesTextTLOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiasRestantesTextTLOU.setText("Dias restantes");
        jPanel1.add(DiasRestantesTextTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, -1));

        FallasPM.setEditable(false);
        FallasPM.setBackground(new java.awt.Color(0, 39, 76));
        FallasPM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FallasPM.setForeground(new java.awt.Color(255, 255, 255));
        FallasPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FallasPM.setText("0");
        FallasPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FallasPMActionPerformed(evt);
            }
        });
        jPanel1.add(FallasPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 50, 40, 40));

        Fallas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fallas.setForeground(new java.awt.Color(255, 255, 255));
        Fallas.setText("Faltas");
        jPanel1.add(Fallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 90, -1, -1));

        GastosMensuales.setEditable(false);
        GastosMensuales.setBackground(new java.awt.Color(0, 39, 76));
        GastosMensuales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GastosMensuales.setForeground(new java.awt.Color(255, 255, 255));
        GastosMensuales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GastosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastosMensualesActionPerformed(evt);
            }
        });
        jPanel1.add(GastosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 260, 120, 30));

        GastosM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GastosM.setForeground(new java.awt.Color(255, 255, 255));
        GastosM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GastosM.setText("Gastos");
        jPanel1.add(GastosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 120, -1));

        UltimoLoteTLOU.setEditable(false);
        UltimoLoteTLOU.setBackground(new java.awt.Color(0, 39, 76));
        UltimoLoteTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UltimoLoteTLOU.setForeground(new java.awt.Color(255, 255, 255));
        UltimoLoteTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UltimoLoteTLOU.setText("0");
        UltimoLoteTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoLoteTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(UltimoLoteTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 200, 30, 30));

        GananciasTextTLOU1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasTextTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        GananciasTextTLOU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GananciasTextTLOU1.setText("Ganancias Lote");
        jPanel1.add(GananciasTextTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 160, -1));

        GananciasUL.setEditable(false);
        GananciasUL.setBackground(new java.awt.Color(0, 39, 76));
        GananciasUL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasUL.setForeground(new java.awt.Color(255, 255, 255));
        GananciasUL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GananciasUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasULActionPerformed(evt);
            }
        });
        jPanel1.add(GananciasUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 200, 160, 30));

        UL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UL.setForeground(new java.awt.Color(255, 255, 255));
        UL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UL.setText("UL");
        jPanel1.add(UL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 180, 30, -1));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Planta 1: The Last Of US");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        Start.setBackground(new java.awt.Color(51, 255, 0));
        Start.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Start.setForeground(new java.awt.Color(255, 255, 255));
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        Stop.setBackground(new java.awt.Color(255, 0, 0));
        Stop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Stop.setForeground(new java.awt.Color(255, 255, 255));
        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });
        jPanel1.add(Stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        IntrosRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IntrosRM.setForeground(new java.awt.Color(255, 255, 255));
        IntrosRM.setText("Intros");
        jPanel1.add(IntrosRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        IniciosRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IniciosRM.setForeground(new java.awt.Color(255, 255, 255));
        IniciosRM.setText("Inicios");
        jPanel1.add(IniciosRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        CredRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CredRM.setForeground(new java.awt.Color(255, 255, 255));
        CredRM.setText("Creditos");
        jPanel1.add(CredRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, -1, -1));

        PlotRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlotRM.setForeground(new java.awt.Color(255, 255, 255));
        PlotRM.setText("Plot Twist");
        jPanel1.add(PlotRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        CierreRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CierreRM.setForeground(new java.awt.Color(255, 255, 255));
        CierreRM.setText("Cierres");
        jPanel1.add(CierreRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, -1, -1));

        CapitulosRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapitulosRM.setForeground(new java.awt.Color(255, 255, 255));
        CapitulosRM.setText("Capitulos");
        jPanel1.add(CapitulosRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 700, -1, -1));

        Empleados1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Empleados1.setForeground(new java.awt.Color(255, 255, 255));
        Empleados1.setText("Empleados");
        jPanel1.add(Empleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, -1, -1));

        EmpEmbRM.setEditable(false);
        EmpEmbRM.setBackground(new java.awt.Color(0, 39, 76));
        EmpEmbRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpEmbRM.setForeground(new java.awt.Color(255, 255, 255));
        EmpEmbRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpEmbRM.setText("0");
        EmpEmbRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpEmbRMActionPerformed(evt);
            }
        });
        jPanel1.add(EmpEmbRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, 30, 30));

        EmpCierreRM.setEditable(false);
        EmpCierreRM.setBackground(new java.awt.Color(0, 39, 76));
        EmpCierreRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpCierreRM.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierreRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpCierreRM.setText("0");
        EmpCierreRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCierreRMActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCierreRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, 30, 30));

        EmpPTwistRM.setEditable(false);
        EmpPTwistRM.setBackground(new java.awt.Color(0, 39, 76));
        EmpPTwistRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpPTwistRM.setForeground(new java.awt.Color(255, 255, 255));
        EmpPTwistRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpPTwistRM.setText("0");
        EmpPTwistRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPTwistRMActionPerformed(evt);
            }
        });
        jPanel1.add(EmpPTwistRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 30, 30));

        EmpCredRM.setEditable(false);
        EmpCredRM.setBackground(new java.awt.Color(0, 39, 76));
        EmpCredRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpCredRM.setForeground(new java.awt.Color(255, 255, 255));
        EmpCredRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpCredRM.setText("0");
        EmpCredRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCredRMActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCredRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 30, 30));

        EmpInicioRM.setEditable(false);
        EmpInicioRM.setBackground(new java.awt.Color(0, 39, 76));
        EmpInicioRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpInicioRM.setForeground(new java.awt.Color(255, 255, 255));
        EmpInicioRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpInicioRM.setText("0");
        EmpInicioRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpInicioRMActionPerformed(evt);
            }
        });
        jPanel1.add(EmpInicioRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 30, 30));

        EmpIntroRM.setEditable(false);
        EmpIntroRM.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntroRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpIntroRM.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntroRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmpIntroRM.setText("0");
        EmpIntroRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroRMActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntroRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 30, 30));

        EmpIntroDesp2.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntroDesp2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpIntroDesp2.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntroDesp2.setText("+");
        EmpIntroDesp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroDesp2ActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntroDesp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 30, 30));

        EmpIntroDesp1.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntroDesp1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpIntroDesp1.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntroDesp1.setText("-");
        EmpIntroDesp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroDesp1ActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntroDesp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 30, 30));

        ProyectMTLOU1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProyectMTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        ProyectMTLOU1.setText("Proyect Manager");
        jPanel1.add(ProyectMTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        FinanzasRM.setEditable(false);
        FinanzasRM.setBackground(new java.awt.Color(0, 39, 76));
        FinanzasRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FinanzasRM.setForeground(new java.awt.Color(255, 255, 255));
        FinanzasRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FinanzasRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinanzasRMActionPerformed(evt);
            }
        });
        jPanel1.add(FinanzasRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 160, 40));

        DiasRestantesTextTLOU1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiasRestantesTextTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        DiasRestantesTextTLOU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiasRestantesTextTLOU1.setText("Dias restantes");
        jPanel1.add(DiasRestantesTextTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 120, -1));

        DiasRestantesRM.setEditable(false);
        DiasRestantesRM.setBackground(new java.awt.Color(0, 39, 76));
        DiasRestantesRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiasRestantesRM.setForeground(new java.awt.Color(255, 255, 255));
        DiasRestantesRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiasRestantesRM.setText("0");
        DiasRestantesRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasRestantesRMActionPerformed(evt);
            }
        });
        jPanel1.add(DiasRestantesRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 40, 40));

        ProyectMTLOU2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProyectMTLOU2.setForeground(new java.awt.Color(255, 255, 255));
        ProyectMTLOU2.setText("Proyect Manager");
        jPanel1.add(ProyectMTLOU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        PMStatuRM.setEditable(false);
        PMStatuRM.setBackground(new java.awt.Color(0, 39, 76));
        PMStatuRM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PMStatuRM.setForeground(new java.awt.Color(255, 255, 255));
        PMStatuRM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PMStatuRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMStatuRMActionPerformed(evt);
            }
        });
        jPanel1.add(PMStatuRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 120, 30));

        ProyectMTLOU3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProyectMTLOU3.setForeground(new java.awt.Color(255, 255, 255));
        ProyectMTLOU3.setText("Director");
        jPanel1.add(ProyectMTLOU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        DirStatuRM1.setEditable(false);
        DirStatuRM1.setBackground(new java.awt.Color(0, 39, 76));
        DirStatuRM1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DirStatuRM1.setForeground(new java.awt.Color(255, 255, 255));
        DirStatuRM1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DirStatuRM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirStatuRM1ActionPerformed(evt);
            }
        });
        jPanel1.add(DirStatuRM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 120, 30));

        ProyectMTLOU4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProyectMTLOU4.setForeground(new java.awt.Color(255, 255, 255));
        ProyectMTLOU4.setText("Gastos");
        jPanel1.add(ProyectMTLOU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, -1, -1));

        GananciasRM1.setEditable(false);
        GananciasRM1.setBackground(new java.awt.Color(0, 39, 76));
        GananciasRM1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasRM1.setForeground(new java.awt.Color(255, 255, 255));
        GananciasRM1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GananciasRM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasRM1ActionPerformed(evt);
            }
        });
        jPanel1.add(GananciasRM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 700, 160, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Proyecto SO HboMax Interface (1366 × 768 px).png"))); // NOI18N
        Fondo.setRequestFocusEnabled(false);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumIntrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIntrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIntrosActionPerformed

    private void NumIniciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIniciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIniciosActionPerformed

    private void NumCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCredActionPerformed

    private void NumPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumPlotActionPerformed

    private void NumCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCierreActionPerformed

    private void CapsTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapsTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapsTLOUActionPerformed

    private void NumEmpIntrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpIntrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpIntrosActionPerformed

    private void NumEmpIniciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpIniciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpIniciosActionPerformed

    private void NumEmpCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpCredActionPerformed

    private void NumEmpPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpPlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpPlotActionPerformed

    private void NumEmpCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpCierreActionPerformed

    private void NumEmpDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpDispoActionPerformed

    private void EmpIntroDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecIntro != 0) {
            hbo.DespProductorIntro();
            hbo.prodIntro--;
        }
    }//GEN-LAST:event_EmpIntroDespActionPerformed

    private void EmpInicioDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpInicioDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecInicio != 0) {
            hbo.DespProductorInicio();
            hbo.prodInicio--;
        }
    }//GEN-LAST:event_EmpInicioDespActionPerformed

    private void EmpCredDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCredDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCred != 0) {
            hbo.DespProductorCred();
            hbo.prodCred--;
        }
    }//GEN-LAST:event_EmpCredDespActionPerformed

    private void EmpPlotDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPlotDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecPlot != 0) {
            hbo.DespProductorPlot();
            hbo.prodPlot--;
        }
    }//GEN-LAST:event_EmpPlotDespActionPerformed

    private void EmpCierreDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCierreDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCierre != 0) {
            hbo.DespProductorCierre();
            hbo.prodCierre--;
        }
    }//GEN-LAST:event_EmpCierreDespActionPerformed

    private void NumEmpEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpEnsambladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpEnsambladorActionPerformed

    private void EmpEnsambladorDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpEnsambladorDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecEnsamblador != 0) {
            hbo.DespProductorE();
            hbo.ensamblador--;
        }
    }//GEN-LAST:event_EmpEnsambladorDespActionPerformed

    private void EmpIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecIntro < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            try {
                hbo.ProductorIntro();
            } catch (InterruptedException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            hbo.prodIntro++;
        }
    }//GEN-LAST:event_EmpIntroActionPerformed

    private void EmpInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpInicioActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecInicio < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorInicio();
            hbo.prodInicio++;
        }
    }//GEN-LAST:event_EmpInicioActionPerformed

    private void EmpCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCredActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCred < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorCred();
            hbo.prodCred++;
        }
    }//GEN-LAST:event_EmpCredActionPerformed

    private void EmpPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPlotActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecPlot < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorPlot();
            hbo.prodPlot++;
        }
    }//GEN-LAST:event_EmpPlotActionPerformed

    private void EmpCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCierreActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCierre < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorCierre();
            hbo.prodCierre++;
        }
    }//GEN-LAST:event_EmpCierreActionPerformed

    private void EmpEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpEnsambladorActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecEnsamblador < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.Ensamblador();
            hbo.ensamblador++;
        }
    }//GEN-LAST:event_EmpEnsambladorActionPerformed

    private void PMStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMStatusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PMStatusActionPerformed

    private void DirTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirTLOUActionPerformed

    private void GananciasTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasTLOUActionPerformed

    private void DiasRestantesTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasRestantesTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasRestantesTLOUActionPerformed

    private void FallasPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FallasPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FallasPMActionPerformed

    private void GastosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastosMensualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GastosMensualesActionPerformed

    private void UltimoLoteTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoLoteTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UltimoLoteTLOUActionPerformed

    private void NumIntrosRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIntrosRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIntrosRMActionPerformed

    private void NumIniciosRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIniciosRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIniciosRMActionPerformed

    private void NumCreditosRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCreditosRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCreditosRMActionPerformed

    private void NumCierresRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCierresRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCierresRMActionPerformed

    private void NumPTwistRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPTwistRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumPTwistRMActionPerformed

    private void NumCapRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCapRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCapRMActionPerformed

    private void GananciasULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasULActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasULActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        //hbo.Start();
        up.start();
    }//GEN-LAST:event_StartActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        // TODO add your handling code here:
        hbo.StopAll();
    }//GEN-LAST:event_StopActionPerformed

    private void EmpIntroRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIntroRMActionPerformed

    private void EmpInicioRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpInicioRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpInicioRMActionPerformed

    private void EmpCredRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCredRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpCredRMActionPerformed

    private void EmpPTwistRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPTwistRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpPTwistRMActionPerformed

    private void EmpCierreRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCierreRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpCierreRMActionPerformed

    private void EmpEmbRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpEmbRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpEmbRMActionPerformed

    private void EmpIntroDesp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroDesp1ActionPerformed
         hbo2.despedirProductorIntros(); 
    }//GEN-LAST:event_EmpIntroDesp1ActionPerformed

    private void EmpIntroDesp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroDesp2ActionPerformed
       hbo2.contratarProductorIntros();
       
    }//GEN-LAST:event_EmpIntroDesp2ActionPerformed

    private void FinanzasRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinanzasRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinanzasRMActionPerformed

    private void DiasRestantesRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasRestantesRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasRestantesRMActionPerformed

    private void PMStatuRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMStatuRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PMStatuRMActionPerformed

    private void DirStatuRM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirStatuRM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirStatuRM1ActionPerformed

    private void GananciasRM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasRM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasRM1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapitulosRM;
    private javax.swing.JLabel CapitulosTLOU;
    public javax.swing.JTextField CapsTLOU;
    private javax.swing.JLabel CierreRM;
    private javax.swing.JLabel CierreTLOU;
    private javax.swing.JLabel CredRM;
    private javax.swing.JLabel CredTLOU;
    public javax.swing.JTextField DiasRestantesRM;
    public javax.swing.JTextField DiasRestantesTLOU;
    private javax.swing.JLabel DiasRestantesTextTLOU;
    private javax.swing.JLabel DiasRestantesTextTLOU1;
    public javax.swing.JTextField DirStatuRM1;
    public javax.swing.JTextField DirTLOU;
    private javax.swing.JLabel DirTextTLOU;
    private javax.swing.JButton EmpCierre;
    private javax.swing.JButton EmpCierreDesp;
    public javax.swing.JTextField EmpCierreRM;
    private javax.swing.JLabel EmpCierreTLOU;
    private javax.swing.JButton EmpCred;
    private javax.swing.JButton EmpCredDesp;
    public javax.swing.JTextField EmpCredRM;
    private javax.swing.JLabel EmpCredsTLOU;
    private javax.swing.JLabel EmpDispoTLOU;
    public javax.swing.JTextField EmpEmbRM;
    private javax.swing.JButton EmpEnsamblador;
    private javax.swing.JButton EmpEnsambladorDesp;
    private javax.swing.JLabel EmpEnsambladorTLOU;
    private javax.swing.JButton EmpInicio;
    private javax.swing.JButton EmpInicioDesp;
    public javax.swing.JTextField EmpInicioRM;
    private javax.swing.JLabel EmpIniciosTLOU;
    private javax.swing.JButton EmpIntro;
    private javax.swing.JButton EmpIntroDesp;
    private javax.swing.JButton EmpIntroDesp1;
    private javax.swing.JButton EmpIntroDesp2;
    public javax.swing.JTextField EmpIntroRM;
    private javax.swing.JLabel EmpIntrosTLOU;
    public javax.swing.JTextField EmpPTwistRM;
    private javax.swing.JButton EmpPlot;
    private javax.swing.JButton EmpPlotDesp;
    private javax.swing.JLabel EmpPlotTLO;
    private javax.swing.JLabel Empleados;
    private javax.swing.JLabel Empleados1;
    private javax.swing.JLabel Fallas;
    public javax.swing.JTextField FallasPM;
    public javax.swing.JTextField FinanzasRM;
    private javax.swing.JLabel Fondo;
    public javax.swing.JTextField GananciasRM1;
    public javax.swing.JTextField GananciasTLOU;
    private javax.swing.JLabel GananciasTextTLOU;
    private javax.swing.JLabel GananciasTextTLOU1;
    public javax.swing.JTextField GananciasUL;
    private javax.swing.JLabel GastosM;
    public javax.swing.JTextField GastosMensuales;
    private javax.swing.JLabel IniciosRM;
    private javax.swing.JLabel IniciosTLOU;
    private javax.swing.JLabel IntrosRM;
    private javax.swing.JLabel IntrosTLOU;
    public javax.swing.JTextField NumCapRM;
    public javax.swing.JTextField NumCierre;
    public javax.swing.JTextField NumCierresRM;
    public javax.swing.JTextField NumCred;
    public javax.swing.JTextField NumCreditosRM;
    public javax.swing.JTextField NumEmpCierre;
    public javax.swing.JTextField NumEmpCred;
    public javax.swing.JTextField NumEmpDispo;
    public javax.swing.JTextField NumEmpEnsamblador;
    public javax.swing.JTextField NumEmpInicios;
    public javax.swing.JTextField NumEmpIntros;
    public javax.swing.JTextField NumEmpPlot;
    public javax.swing.JTextField NumInicios;
    public javax.swing.JTextField NumIniciosRM;
    public javax.swing.JTextField NumIntros;
    public javax.swing.JTextField NumIntrosRM;
    public javax.swing.JTextField NumPTwistRM;
    public javax.swing.JTextField NumPlot;
    public javax.swing.JTextField PMStatuRM;
    public javax.swing.JTextField PMStatus;
    private javax.swing.JLabel PlotRM;
    private javax.swing.JLabel PlotTLOU;
    private javax.swing.JLabel Produccion;
    private javax.swing.JLabel Produccion4;
    private javax.swing.JLabel ProyectMTLOU;
    private javax.swing.JLabel ProyectMTLOU1;
    private javax.swing.JLabel ProyectMTLOU2;
    private javax.swing.JLabel ProyectMTLOU3;
    private javax.swing.JLabel ProyectMTLOU4;
    private javax.swing.JButton Start;
    private javax.swing.JButton Stop;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel UL;
    public javax.swing.JTextField UltimoLoteTLOU;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
