/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_SO;

import Proyecto_SO.Clases.PlantaTLOU.HBO1;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author frand
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     * 
     */
    
    private Actualizador up;
    HBO1 hbo = new HBO1();
    int inicios =0;
    
    public Dashboard() throws FileNotFoundException, InterruptedException, ParseException{
        initComponents();
        this.up = new Actualizador(this, this.hbo);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        
        
        
      
    }
    /**public void Reinicio(){
    up.Reinicio();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Produccion = new javax.swing.JLabel();
        Empleados = new javax.swing.JLabel();
        NumIntros = new javax.swing.JTextField();
        IntrosTLOU = new javax.swing.JLabel();
        NumInicios = new javax.swing.JTextField();
        IniciosTLOU = new javax.swing.JLabel();
        NumCred = new javax.swing.JTextField();
        CredTLOU = new javax.swing.JLabel();
        NumPlot = new javax.swing.JTextField();
        PlotTLOU = new javax.swing.JLabel();
        NumCierre = new javax.swing.JTextField();
        CierreTLOU = new javax.swing.JLabel();
        CapsTLOU = new javax.swing.JTextField();
        CapitulosTLOU = new javax.swing.JLabel();
        NumEmpIntros = new javax.swing.JTextField();
        EmpIntrosTLOU = new javax.swing.JLabel();
        NumEmpInicios = new javax.swing.JTextField();
        EmpIniciosTLOU = new javax.swing.JLabel();
        NumEmpCred = new javax.swing.JTextField();
        EmpCredsTLOU = new javax.swing.JLabel();
        NumEmpPlot = new javax.swing.JTextField();
        EmpPlotTLO = new javax.swing.JLabel();
        NumEmpCierre = new javax.swing.JTextField();
        EmpCierreTLOU = new javax.swing.JLabel();
        NumEmpDispo = new javax.swing.JTextField();
        EmpDispoTLOU = new javax.swing.JLabel();
        NumEmpEnsamblador = new javax.swing.JTextField();
        EmpEnsambladorTLOU = new javax.swing.JLabel();
        EmpIntroDesp = new javax.swing.JButton();
        EmpInicioDesp = new javax.swing.JButton();
        EmpCredDesp = new javax.swing.JButton();
        EmpPlotDesp = new javax.swing.JButton();
        EmpCierreDesp = new javax.swing.JButton();
        EmpEnsambladorDesp = new javax.swing.JButton();
        EmpIntro = new javax.swing.JButton();
        EmpInicio = new javax.swing.JButton();
        EmpCred = new javax.swing.JButton();
        EmpPlot = new javax.swing.JButton();
        EmpCierre = new javax.swing.JButton();
        EmpEnsamblador = new javax.swing.JButton();
        PMStatus = new javax.swing.JTextField();
        ProyectMTLOU = new javax.swing.JLabel();
        DirTLOU = new javax.swing.JTextField();
        DirTextTLOU = new javax.swing.JLabel();
        GananciasTLOU = new javax.swing.JTextField();
        GananciasTextTLOU = new javax.swing.JLabel();
        DiasRestantesTLOU = new javax.swing.JTextField();
        DiasRestantesTextTLOU = new javax.swing.JLabel();
        FallasPM = new javax.swing.JTextField();
        Fallas = new javax.swing.JLabel();
        GastosMensuales = new javax.swing.JTextField();
        GastosM = new javax.swing.JLabel();
        UltimoLoteTLOU = new javax.swing.JTextField();
        GananciasUL = new javax.swing.JTextField();
        UL = new javax.swing.JLabel();
        GananciasULTextTLOU1 = new javax.swing.JLabel();
        InicioProdu = new javax.swing.JButton();
        StopProdu = new javax.swing.JButton();
        Produccion1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Produccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Produccion.setForeground(new java.awt.Color(255, 255, 255));
        Produccion.setText("Produccion");
        jPanel1.add(Produccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        Empleados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Empleados.setForeground(new java.awt.Color(255, 255, 255));
        Empleados.setText("Empleados");
        jPanel1.add(Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, -1, -1));

        NumIntros.setEditable(false);
        NumIntros.setBackground(new java.awt.Color(0, 39, 76));
        NumIntros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumIntros.setForeground(new java.awt.Color(255, 255, 255));
        NumIntros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumIntros.setText("0");
        NumIntros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIntrosActionPerformed(evt);
            }
        });
        jPanel1.add(NumIntros, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 30, 30));

        IntrosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IntrosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        IntrosTLOU.setText("Intros");
        jPanel1.add(IntrosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        NumInicios.setEditable(false);
        NumInicios.setBackground(new java.awt.Color(0, 39, 76));
        NumInicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumInicios.setForeground(new java.awt.Color(255, 255, 255));
        NumInicios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumInicios.setText("0");
        NumInicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumIniciosActionPerformed(evt);
            }
        });
        jPanel1.add(NumInicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 30, 30));

        IniciosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IniciosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        IniciosTLOU.setText("Inicios");
        jPanel1.add(IniciosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, -1));

        NumCred.setEditable(false);
        NumCred.setBackground(new java.awt.Color(0, 39, 76));
        NumCred.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCred.setForeground(new java.awt.Color(255, 255, 255));
        NumCred.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCred.setText("0");
        NumCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCredActionPerformed(evt);
            }
        });
        jPanel1.add(NumCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 30, 30));

        CredTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CredTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CredTLOU.setText("Creditos");
        jPanel1.add(CredTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        NumPlot.setEditable(false);
        NumPlot.setBackground(new java.awt.Color(0, 39, 76));
        NumPlot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumPlot.setForeground(new java.awt.Color(255, 255, 255));
        NumPlot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumPlot.setText("0");
        NumPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPlotActionPerformed(evt);
            }
        });
        jPanel1.add(NumPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 30, 30));

        PlotTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PlotTLOU.setForeground(new java.awt.Color(255, 255, 255));
        PlotTLOU.setText("Plot Twist");
        jPanel1.add(PlotTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        NumCierre.setEditable(false);
        NumCierre.setBackground(new java.awt.Color(0, 39, 76));
        NumCierre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumCierre.setForeground(new java.awt.Color(255, 255, 255));
        NumCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumCierre.setText("0");
        NumCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumCierreActionPerformed(evt);
            }
        });
        jPanel1.add(NumCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 30, 30));

        CierreTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CierreTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CierreTLOU.setText("Cierres");
        jPanel1.add(CierreTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        CapsTLOU.setEditable(false);
        CapsTLOU.setBackground(new java.awt.Color(0, 39, 76));
        CapsTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapsTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CapsTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CapsTLOU.setText("0");
        CapsTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapsTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(CapsTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 30, 30));

        CapitulosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapitulosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        CapitulosTLOU.setText("Capitulos");
        jPanel1.add(CapitulosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        NumEmpIntros.setEditable(false);
        NumEmpIntros.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpIntros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpIntros.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpIntros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpIntros.setText("0");
        NumEmpIntros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpIntrosActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpIntros, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 30, 30));

        EmpIntrosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpIntrosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntrosTLOU.setText("Intros");
        jPanel1.add(EmpIntrosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, -1, -1));

        NumEmpInicios.setEditable(false);
        NumEmpInicios.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpInicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpInicios.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpInicios.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpInicios.setText("0");
        NumEmpInicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpIniciosActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpInicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 30, 30));

        EmpIniciosTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpIniciosTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpIniciosTLOU.setText("Inicios");
        jPanel1.add(EmpIniciosTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, -1, -1));

        NumEmpCred.setEditable(false);
        NumEmpCred.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpCred.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpCred.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpCred.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpCred.setText("0");
        NumEmpCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpCredActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 180, 30, 30));

        EmpCredsTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpCredsTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpCredsTLOU.setText("Creditos");
        jPanel1.add(EmpCredsTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, -1, -1));

        NumEmpPlot.setEditable(false);
        NumEmpPlot.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpPlot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpPlot.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpPlot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpPlot.setText("0");
        NumEmpPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpPlotActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 30, 30));

        EmpPlotTLO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpPlotTLO.setForeground(new java.awt.Color(255, 255, 255));
        EmpPlotTLO.setText("Plot Twist");
        jPanel1.add(EmpPlotTLO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 230, -1, -1));

        NumEmpCierre.setEditable(false);
        NumEmpCierre.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpCierre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpCierre.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpCierre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpCierre.setText("0");
        NumEmpCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpCierreActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 30, 30));

        EmpCierreTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpCierreTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierreTLOU.setText("Cierres");
        jPanel1.add(EmpCierreTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, -1, -1));

        NumEmpDispo.setEditable(false);
        NumEmpDispo.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpDispo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpDispo.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpDispo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpDispo.setText("0");
        NumEmpDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpDispoActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 30, 30));

        EmpDispoTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpDispoTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpDispoTLOU.setText("Disponibles");
        jPanel1.add(EmpDispoTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, -1, -1));

        NumEmpEnsamblador.setEditable(false);
        NumEmpEnsamblador.setBackground(new java.awt.Color(0, 39, 76));
        NumEmpEnsamblador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NumEmpEnsamblador.setForeground(new java.awt.Color(255, 255, 255));
        NumEmpEnsamblador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NumEmpEnsamblador.setText("0");
        NumEmpEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumEmpEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(NumEmpEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 30, 30));

        EmpEnsambladorTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmpEnsambladorTLOU.setForeground(new java.awt.Color(255, 255, 255));
        EmpEnsambladorTLOU.setText("Ensamblador");
        jPanel1.add(EmpEnsambladorTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, -1, -1));

        EmpIntroDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntroDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpIntroDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntroDesp.setText("-");
        EmpIntroDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntroDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, 30));

        EmpInicioDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpInicioDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpInicioDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpInicioDesp.setText("-");
        EmpInicioDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpInicioDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpInicioDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, 30));

        EmpCredDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpCredDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpCredDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpCredDesp.setText("-");
        EmpCredDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCredDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCredDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, -1, 30));

        EmpPlotDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpPlotDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpPlotDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpPlotDesp.setText("-");
        EmpPlotDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPlotDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpPlotDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, 30));

        EmpCierreDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpCierreDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpCierreDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierreDesp.setText("-");
        EmpCierreDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCierreDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCierreDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, -1, 30));

        EmpEnsambladorDesp.setBackground(new java.awt.Color(0, 39, 76));
        EmpEnsambladorDesp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmpEnsambladorDesp.setForeground(new java.awt.Color(255, 255, 255));
        EmpEnsambladorDesp.setText("-");
        EmpEnsambladorDesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpEnsambladorDespActionPerformed(evt);
            }
        });
        jPanel1.add(EmpEnsambladorDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, -1, 30));

        EmpIntro.setBackground(new java.awt.Color(0, 39, 76));
        EmpIntro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpIntro.setForeground(new java.awt.Color(255, 255, 255));
        EmpIntro.setText("+");
        EmpIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIntroActionPerformed(evt);
            }
        });
        jPanel1.add(EmpIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, -1, 30));

        EmpInicio.setBackground(new java.awt.Color(0, 39, 76));
        EmpInicio.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpInicio.setForeground(new java.awt.Color(255, 255, 255));
        EmpInicio.setText("+");
        EmpInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpInicioActionPerformed(evt);
            }
        });
        jPanel1.add(EmpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, -1, 30));

        EmpCred.setBackground(new java.awt.Color(0, 39, 76));
        EmpCred.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpCred.setForeground(new java.awt.Color(255, 255, 255));
        EmpCred.setText("+");
        EmpCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCredActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, -1, 30));

        EmpPlot.setBackground(new java.awt.Color(0, 39, 76));
        EmpPlot.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpPlot.setForeground(new java.awt.Color(255, 255, 255));
        EmpPlot.setText("+");
        EmpPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPlotActionPerformed(evt);
            }
        });
        jPanel1.add(EmpPlot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, -1, 30));

        EmpCierre.setBackground(new java.awt.Color(0, 39, 76));
        EmpCierre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpCierre.setForeground(new java.awt.Color(255, 255, 255));
        EmpCierre.setText("+");
        EmpCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpCierreActionPerformed(evt);
            }
        });
        jPanel1.add(EmpCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, -1, 30));

        EmpEnsamblador.setBackground(new java.awt.Color(0, 39, 76));
        EmpEnsamblador.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        EmpEnsamblador.setForeground(new java.awt.Color(255, 255, 255));
        EmpEnsamblador.setText("+");
        EmpEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpEnsambladorActionPerformed(evt);
            }
        });
        jPanel1.add(EmpEnsamblador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, -1, 30));

        PMStatus.setEditable(false);
        PMStatus.setBackground(new java.awt.Color(0, 39, 76));
        PMStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PMStatus.setForeground(new java.awt.Color(255, 255, 255));
        PMStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PMStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMStatusActionPerformed(evt);
            }
        });
        jPanel1.add(PMStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, 120, 30));

        ProyectMTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ProyectMTLOU.setForeground(new java.awt.Color(255, 255, 255));
        ProyectMTLOU.setText("Proyect Manager");
        jPanel1.add(ProyectMTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        DirTLOU.setEditable(false);
        DirTLOU.setBackground(new java.awt.Color(0, 39, 76));
        DirTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DirTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DirTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DirTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(DirTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 130, 120, 30));

        DirTextTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DirTextTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DirTextTLOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DirTextTLOU.setText("Director");
        jPanel1.add(DirTextTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 110, 120, -1));

        GananciasTLOU.setEditable(false);
        GananciasTLOU.setBackground(new java.awt.Color(0, 39, 76));
        GananciasTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasTLOU.setForeground(new java.awt.Color(255, 255, 255));
        GananciasTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GananciasTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(GananciasTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 260, 30));

        GananciasTextTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasTextTLOU.setForeground(new java.awt.Color(255, 255, 255));
        GananciasTextTLOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GananciasTextTLOU.setText("Ganancias totales:");
        jPanel1.add(GananciasTextTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 117, 260, 20));

        DiasRestantesTLOU.setEditable(false);
        DiasRestantesTLOU.setBackground(new java.awt.Color(0, 39, 76));
        DiasRestantesTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiasRestantesTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DiasRestantesTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiasRestantesTLOU.setText("0");
        DiasRestantesTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiasRestantesTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(DiasRestantesTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, 40, 40));

        DiasRestantesTextTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiasRestantesTextTLOU.setForeground(new java.awt.Color(255, 255, 255));
        DiasRestantesTextTLOU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiasRestantesTextTLOU.setText("Dias restantes");
        jPanel1.add(DiasRestantesTextTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 120, -1));

        FallasPM.setEditable(false);
        FallasPM.setBackground(new java.awt.Color(0, 39, 76));
        FallasPM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FallasPM.setForeground(new java.awt.Color(255, 255, 255));
        FallasPM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FallasPM.setText("0");
        FallasPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FallasPMActionPerformed(evt);
            }
        });
        jPanel1.add(FallasPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 50, 40, 40));

        Fallas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fallas.setForeground(new java.awt.Color(255, 255, 255));
        Fallas.setText("Faltas");
        jPanel1.add(Fallas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 90, -1, -1));

        GastosMensuales.setEditable(false);
        GastosMensuales.setBackground(new java.awt.Color(0, 39, 76));
        GastosMensuales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GastosMensuales.setForeground(new java.awt.Color(255, 255, 255));
        GastosMensuales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GastosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastosMensualesActionPerformed(evt);
            }
        });
        jPanel1.add(GastosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 260, 120, 30));

        GastosM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GastosM.setForeground(new java.awt.Color(255, 255, 255));
        GastosM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GastosM.setText("Gastos");
        jPanel1.add(GastosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 240, 120, -1));

        UltimoLoteTLOU.setEditable(false);
        UltimoLoteTLOU.setBackground(new java.awt.Color(0, 39, 76));
        UltimoLoteTLOU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UltimoLoteTLOU.setForeground(new java.awt.Color(255, 255, 255));
        UltimoLoteTLOU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UltimoLoteTLOU.setText("0");
        UltimoLoteTLOU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoLoteTLOUActionPerformed(evt);
            }
        });
        jPanel1.add(UltimoLoteTLOU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 200, 30, 30));

        GananciasUL.setEditable(false);
        GananciasUL.setBackground(new java.awt.Color(0, 39, 76));
        GananciasUL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasUL.setForeground(new java.awt.Color(255, 255, 255));
        GananciasUL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GananciasUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GananciasULActionPerformed(evt);
            }
        });
        jPanel1.add(GananciasUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 200, 160, 30));

        UL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UL.setForeground(new java.awt.Color(255, 255, 255));
        UL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UL.setText("UL");
        jPanel1.add(UL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 180, 30, -1));

        GananciasULTextTLOU1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GananciasULTextTLOU1.setForeground(new java.awt.Color(255, 255, 255));
        GananciasULTextTLOU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GananciasULTextTLOU1.setText("Ganancias UL:");
        jPanel1.add(GananciasULTextTLOU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 160, -1));

        InicioProdu.setBackground(new java.awt.Color(0, 255, 0));
        InicioProdu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        InicioProdu.setForeground(new java.awt.Color(255, 255, 255));
        InicioProdu.setText("Producir");
        InicioProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioProduActionPerformed(evt);
            }
        });
        jPanel1.add(InicioProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 330, -1, -1));

        StopProdu.setBackground(new java.awt.Color(255, 51, 51));
        StopProdu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        StopProdu.setForeground(new java.awt.Color(255, 255, 255));
        StopProdu.setText("Stop");
        StopProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopProduActionPerformed(evt);
            }
        });
        jPanel1.add(StopProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 330, -1, -1));

        Produccion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Produccion1.setForeground(new java.awt.Color(255, 255, 255));
        Produccion1.setText("Planta 1: The Last Of Us");
        jPanel1.add(Produccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Proyecto SO HboMax Interface (1366 × 768 px).png"))); // NOI18N
        Fondo.setRequestFocusEnabled(false);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumIntrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIntrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIntrosActionPerformed

    private void NumIniciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumIniciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumIniciosActionPerformed

    private void NumCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCredActionPerformed

    private void NumPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumPlotActionPerformed

    private void NumCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumCierreActionPerformed

    private void CapsTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapsTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapsTLOUActionPerformed

    private void NumEmpIntrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpIntrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpIntrosActionPerformed

    private void NumEmpIniciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpIniciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpIniciosActionPerformed

    private void NumEmpCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpCredActionPerformed

    private void NumEmpPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpPlotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpPlotActionPerformed

    private void NumEmpCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpCierreActionPerformed

    private void NumEmpDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpDispoActionPerformed

    private void EmpIntroDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecIntro != 0) {
            hbo.DespProductorIntro();
            hbo.prodIntro--;
        }
    }//GEN-LAST:event_EmpIntroDespActionPerformed

    private void EmpInicioDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpInicioDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecInicio != 0) {
            hbo.DespProductorInicio();
            hbo.prodInicio--;
        }
    }//GEN-LAST:event_EmpInicioDespActionPerformed

    private void EmpCredDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCredDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCred != 0) {
            hbo.DespProductorCred();
            hbo.prodCred--;
        }
    }//GEN-LAST:event_EmpCredDespActionPerformed

    private void EmpPlotDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPlotDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecPlot != 0) {
            hbo.DespProductorPlot();
            hbo.prodPlot--;
        }
    }//GEN-LAST:event_EmpPlotDespActionPerformed

    private void EmpCierreDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCierreDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCierre != 0) {
            hbo.DespProductorCierre();
            hbo.prodCierre--;
        }
    }//GEN-LAST:event_EmpCierreDespActionPerformed

    private void NumEmpEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumEmpEnsambladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumEmpEnsambladorActionPerformed

    private void EmpEnsambladorDespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpEnsambladorDespActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecEnsamblador != 0) {
            hbo.DespProductorE();
            hbo.ensamblador--;
        }
    }//GEN-LAST:event_EmpEnsambladorDespActionPerformed

    private void EmpIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIntroActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecIntro < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            try {
                hbo.ProductorIntro();
            } catch (InterruptedException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            hbo.prodIntro++;
        }
    }//GEN-LAST:event_EmpIntroActionPerformed

    private void EmpInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpInicioActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecInicio < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorInicio();
            hbo.prodInicio++;
        }
    }//GEN-LAST:event_EmpInicioActionPerformed

    private void EmpCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCredActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCred < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorCred();
            hbo.prodCred++;
        }
    }//GEN-LAST:event_EmpCredActionPerformed

    private void EmpPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPlotActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecPlot < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorPlot();
            hbo.prodPlot++;
        }
    }//GEN-LAST:event_EmpPlotActionPerformed

    private void EmpCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCierreActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecCierre < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.ProductorCierre();
            hbo.prodCierre++;
        }
    }//GEN-LAST:event_EmpCierreActionPerformed

    private void EmpEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpEnsambladorActionPerformed
        // TODO add your handling code here:
        if (hbo.PosVecEnsamblador < hbo.empleadosMax && (hbo.empleadosMax -(hbo.prodIntro+hbo.prodInicio+hbo.prodCred+hbo.prodPlot+hbo.prodCierre+hbo.ensamblador) !=0)) {
            hbo.Ensamblador();
            hbo.ensamblador++;
        }
    }//GEN-LAST:event_EmpEnsambladorActionPerformed

    private void PMStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMStatusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PMStatusActionPerformed

    private void DirTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirTLOUActionPerformed

    private void GananciasTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasTLOUActionPerformed

    private void DiasRestantesTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiasRestantesTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiasRestantesTLOUActionPerformed

    private void FallasPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FallasPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FallasPMActionPerformed

    private void GastosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastosMensualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GastosMensualesActionPerformed

    private void UltimoLoteTLOUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoLoteTLOUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UltimoLoteTLOUActionPerformed

    private void InicioProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioProduActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            hbo.Start();
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.up.start();
    
    }//GEN-LAST:event_InicioProduActionPerformed

    private void StopProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopProduActionPerformed
        // TODO add your handling code here:
        //this.up.stop();
        hbo.StopAll();
    }//GEN-LAST:event_StopProduActionPerformed

    private void GananciasULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GananciasULActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GananciasULActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CapitulosTLOU;
    public javax.swing.JTextField CapsTLOU;
    private javax.swing.JLabel CierreTLOU;
    private javax.swing.JLabel CredTLOU;
    public javax.swing.JTextField DiasRestantesTLOU;
    private javax.swing.JLabel DiasRestantesTextTLOU;
    public javax.swing.JTextField DirTLOU;
    private javax.swing.JLabel DirTextTLOU;
    private javax.swing.JButton EmpCierre;
    private javax.swing.JButton EmpCierreDesp;
    private javax.swing.JLabel EmpCierreTLOU;
    private javax.swing.JButton EmpCred;
    private javax.swing.JButton EmpCredDesp;
    private javax.swing.JLabel EmpCredsTLOU;
    private javax.swing.JLabel EmpDispoTLOU;
    private javax.swing.JButton EmpEnsamblador;
    private javax.swing.JButton EmpEnsambladorDesp;
    private javax.swing.JLabel EmpEnsambladorTLOU;
    private javax.swing.JButton EmpInicio;
    private javax.swing.JButton EmpInicioDesp;
    private javax.swing.JLabel EmpIniciosTLOU;
    private javax.swing.JButton EmpIntro;
    private javax.swing.JButton EmpIntroDesp;
    private javax.swing.JLabel EmpIntrosTLOU;
    private javax.swing.JButton EmpPlot;
    private javax.swing.JButton EmpPlotDesp;
    private javax.swing.JLabel EmpPlotTLO;
    private javax.swing.JLabel Empleados;
    private javax.swing.JLabel Fallas;
    public javax.swing.JTextField FallasPM;
    private javax.swing.JLabel Fondo;
    public javax.swing.JTextField GananciasTLOU;
    private javax.swing.JLabel GananciasTextTLOU;
    public javax.swing.JTextField GananciasUL;
    private javax.swing.JLabel GananciasULTextTLOU1;
    private javax.swing.JLabel GastosM;
    public javax.swing.JTextField GastosMensuales;
    private javax.swing.JButton InicioProdu;
    private javax.swing.JLabel IniciosTLOU;
    private javax.swing.JLabel IntrosTLOU;
    public javax.swing.JTextField NumCierre;
    public javax.swing.JTextField NumCred;
    public javax.swing.JTextField NumEmpCierre;
    public javax.swing.JTextField NumEmpCred;
    public javax.swing.JTextField NumEmpDispo;
    public javax.swing.JTextField NumEmpEnsamblador;
    public javax.swing.JTextField NumEmpInicios;
    public javax.swing.JTextField NumEmpIntros;
    public javax.swing.JTextField NumEmpPlot;
    public javax.swing.JTextField NumInicios;
    public javax.swing.JTextField NumIntros;
    public javax.swing.JTextField NumPlot;
    public javax.swing.JTextField PMStatus;
    private javax.swing.JLabel PlotTLOU;
    private javax.swing.JLabel Produccion;
    private javax.swing.JLabel Produccion1;
    private javax.swing.JLabel ProyectMTLOU;
    private javax.swing.JButton StopProdu;
    private javax.swing.JLabel UL;
    public javax.swing.JTextField UltimoLoteTLOU;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
